default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
