services:
  mobilic-db:
    image: postgres:13.7-alpine
    container_name: mobilic-db
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mobilic
      POSTGRES_USER: mobilic
      POSTGRES_PASSWORD: mobilic
    volumes:
      - mobilic-postgresql-data:/var/lib/postgresql

  mobilic-db-test:
    image: postgres:13.7-alpine
    ports:
      - "5433:5432"
    environment: 
      POSTGRES_DB: mobilic-test
      POSTGRES_USER: mobilic-test
      POSTGRES_PASSWORD: mobilic-test

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"


volumes:
  mobilic-postgresql-data: