version: '3.5'
services:
  mobilic-db:
    image: postgres:12.4-alpine
    container_name: mobilic-db
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mobilic
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - mobilic-postgresql-data:/var/lib/postgresql

volumes:
  mobilic-postgresql-data: