version: '3.5'
services:
  # mobilic-api:
  #   image: python:3.9.2-slim
  #   command: sh -c "apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/* && /usr/local/bin/python -m pip install --upgrade pip && pip install -r requirements-dev.txt && flask db upgrade && flask run --host 0.0.0.0"
  #   ports: 
  #     - "5000:5000"
  #   environment:
  #     FLASK_APP: app:app
  #     FLASK_DEBUG: "1"
  #     FLASK_SKIP_DOTENV: "1"
  #     DOTENV_FILE: ".env/.env.local"
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - mobilic-db
  #     - redis
  
  mobilic-db:
    image: postgres:13.6-alpine
    container_name: mobilic-db
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mobilic
      POSTGRES_USER: mobilic
      POSTGRES_PASSWORD: mobilic
    volumes:
      - mobilic-postgresql-data:/var/lib/postgresql

  mobilic-db-test:
    image: postgres:13.6-alpine
    ports:
      - "5433:5432"
    environment: 
      POSTGRES_DB: mobilic-test
      POSTGRES_USER: mobilic-test
      POSTGRES_PASSWORD: mobilic-test

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"


volumes:
  mobilic-postgresql-data: