"""Add mission validation

Revision ID: 020c5cbf1354
Revises: d4f359418780
Create Date: 2020-05-07 14:00:13.536942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "020c5cbf1354"
down_revision = "d4f359418780"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mission_validation",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.Column("submitter_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["mission_id"], ["mission.id"],),
        sa.ForeignKeyConstraint(["submitter_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mission_validation_mission_id"),
        "mission_validation",
        ["mission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mission_validation_submitter_id"),
        "mission_validation",
        ["submitter_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_mission_validation_submitter_id"),
        table_name="mission_validation",
    )
    op.drop_index(
        op.f("ix_mission_validation_mission_id"),
        table_name="mission_validation",
    )
    op.drop_table("mission_validation")
    # ### end Alembic commands ###
