"""add mailing method to employment

Revision ID: 0722a03fd71e
Revises: 749ceabbea95
Create Date: 2020-07-21 08:35:06.000198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0722a03fd71e"
down_revision = "749ceabbea95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employment",
        sa.Column("invite_token", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "employment", sa.Column("email", sa.String(length=255), nullable=True)
    )
    op.alter_column(
        "employment", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_unique_constraint(None, "employment", ["invite_token"])
    op.create_check_constraint(
        "either_user_id_or_invite_token_is_set",
        "employment",
        "((user_id is not null)::bool != (invite_token is not null)::bool)",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "employment", type_="unique")
    op.alter_column(
        "employment", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint("either_user_id_or_invite_token_is_set", "employment")
    op.drop_column("employment", "invite_token")
    op.drop_column("employment", "email")
    # ### end Alembic commands ###
