"""Add cancellation time to expenditure

Revision ID: 0f0d912567c0
Revises: 112cfb414cb6
Create Date: 2020-02-28 12:21:02.252737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0f0d912567c0"
down_revision = "112cfb414cb6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expenditure", sa.Column("cancelled_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenditure", "cancelled_at")
    # ### end Alembic commands ###
