"""Add comments

Revision ID: 112cfb414cb6
Revises: 8fde055f9d29
Create Date: 2020-02-17 02:05:20.315985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "112cfb414cb6"
down_revision = "8fde055f9d29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column("reception_time", sa.DateTime(), nullable=False),
        sa.Column(
            "validation_status",
            sa.Enum(
                "validated",
                "pending",
                "rejected",
                "unauthorized_submitter",
                name="eventbasevalidationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("submitter_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitter_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_comment_company_id"), "comment", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_comment_submitter_id"),
        "comment",
        ["submitter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_comment_user_id"), "comment", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comment_user_id"), table_name="comment")
    op.drop_index(op.f("ix_comment_submitter_id"), table_name="comment")
    op.drop_index(op.f("ix_comment_company_id"), table_name="comment")
    op.drop_table("comment")
    # ### end Alembic commands ###
