"""Emails

Revision ID: 119d8d9a324c
Revises: 41e74d769002
Create Date: 2021-03-25 14:30:53.666126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "119d8d9a324c"
down_revision = "41e74d769002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("mailjet_id", sa.TEXT(), nullable=False),
        sa.Column("address", sa.TEXT(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "account_activation",
                "company_creation",
                "employment_validation_confirmation",
                "invitation",
                "mission_changes_warning",
                "reset_password",
                "worker_onboarding_first_info",
                "worker_onboarding_second_info",
                "manager_onboarding_first_info",
                "manager_onboarding_second_info",
                name="emailtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("employment_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["employment_id"], ["employment.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mailjet_id"),
    )
    op.create_index(
        op.f("ix_email_employment_id"),
        "email",
        ["employment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_user_id"), "email", ["user_id"], unique=False
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_user_id"), table_name="email")
    op.drop_index(op.f("ix_email_employment_id"), table_name="email")
    op.drop_table("email")
    # ### end Alembic commands ###
