"""Add dismiss reception time

Revision ID: 1517112ecb4d
Revises: a318018bd9fb
Create Date: 2020-03-08 22:43:39.955986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1517112ecb4d"
down_revision = "a318018bd9fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity",
        sa.Column("dismiss_received_at", sa.DateTime(), nullable=True),
    )
    op.execute("UPDATE activity SET dismiss_received_at = dismissed_at")
    op.add_column(
        "comment",
        sa.Column("dismiss_received_at", sa.DateTime(), nullable=True),
    )
    op.execute("UPDATE comment SET dismiss_received_at = dismissed_at")
    op.add_column(
        "expenditure",
        sa.Column("dismiss_received_at", sa.DateTime(), nullable=True),
    )
    op.execute("UPDATE expenditure SET dismiss_received_at = dismissed_at")
    op.drop_constraint("non_nullable_dismiss_type", "activity")
    op.drop_constraint("non_nullable_dismiss_type", "comment")
    op.drop_constraint("non_nullable_dismiss_type", "expenditure")
    op.create_check_constraint(
        "non_nullable_dismiss_type",
        "activity",
        "((dismissed_at is not null)::bool = (dismiss_type is not null)::bool AND (dismiss_type is not null)::bool = (dismiss_received_at is not null)::bool)",
    )
    op.create_check_constraint(
        "non_nullable_dismiss_type",
        "comment",
        "((dismissed_at is not null)::bool = (dismiss_type is not null)::bool AND (dismiss_type is not null)::bool = (dismiss_received_at is not null)::bool)",
    )
    op.create_check_constraint(
        "non_nullable_dismiss_type",
        "expenditure",
        "((dismissed_at is not null)::bool = (dismiss_type is not null)::bool AND (dismiss_type is not null)::bool = (dismiss_received_at is not null)::bool)",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenditure", "dismiss_received_at")
    op.drop_column("comment", "dismiss_received_at")
    op.drop_column("activity", "dismiss_received_at")
    op.drop_constraint("non_nullable_dismiss_type", "activity")
    op.drop_constraint("non_nullable_dismiss_type", "comment")
    op.drop_constraint("non_nullable_dismiss_type", "expenditure")
    op.create_check_constraint(
        "non_nullable_dismiss_type",
        "activity",
        "((dismissed_at is not null)::bool = (dismiss_type is not null)::bool)",
    )
    op.create_check_constraint(
        "non_nullable_dismiss_type",
        "comment",
        "((dismissed_at is not null)::bool = (dismiss_type is not null)::bool)",
    )
    op.create_check_constraint(
        "non_nullable_dismiss_type",
        "expenditure",
        "((dismissed_at is not null)::bool = (dismiss_type is not null)::bool)",
    )
    # ### end Alembic commands ###
