"""Add france connect info

Revision ID: 17a9939344be
Revises: 771c404ddbc2
Create Date: 2020-08-10 16:26:22.860892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "17a9939344be"
down_revision = "771c404ddbc2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("france_connect_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column(
            "france_connect_info",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.create_unique_constraint(None, "user", ["france_connect_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "france_connect_info")
    op.drop_column("user", "france_connect_id")
    # ### end Alembic commands ###
