"""Add anonymized expenditure table

Revision ID: 1984298b9170
Revises: b016c0aa50e0
Create Date: 2024-11-18 10:31:16.942438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1984298b9170"
down_revision = "b016c0aa50e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenditure_anonymized",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mission_d", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=10), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("submitter_id", sa.Integer(), nullable=True),
        sa.Column("dismiss_author_id", sa.Integer(), nullable=True),
        sa.Column("creation_time", sa.DateTime(), nullable=True),
        sa.Column("reception_time", sa.DateTime(), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(), nullable=True),
        sa.Column("spending__date", sa.DateTime(), nullable=True),
        sa.Column("dismiss_context", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expenditure_anonymized")
    # ### end Alembic commands ###
