"""Add Naf codes

Revision ID: 1e07913658d1
Revises: 3edf5de0351f
Create Date: 2021-04-20 17:11:05.505938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1e07913658d1"
down_revision = "3edf5de0351f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "naf_code",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("code", sa.TEXT(), nullable=False),
        sa.Column("label", sa.TEXT(), nullable=False),
        sa.Column("section_code", sa.TEXT(), nullable=False),
        sa.Column("section_label", sa.TEXT(), nullable=False),
        sa.Column("level1_code", sa.TEXT(), nullable=False),
        sa.Column("level1_label", sa.TEXT(), nullable=False),
        sa.Column("level2_code", sa.TEXT(), nullable=False),
        sa.Column("level2_label", sa.TEXT(), nullable=False),
        sa.Column("level3_code", sa.TEXT(), nullable=False),
        sa.Column("level3_label", sa.TEXT(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_naf_code_code"), "naf_code", ["code"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("naf_code")
    # ### end Alembic commands ###
