"""oauth

Revision ID: 2e6b59be046b
Revises: f02e61a44fa3
Create Date: 2020-08-18 15:33:53.215823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e6b59be046b"
down_revision = "f02e61a44fa3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth2_client",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("secret", sa.String(length=120), nullable=False),
        sa.Column("redirect_uris", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "oauth2_authorization_code",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("redirect_uri", sa.Text(), nullable=True),
        sa.Column("response_type", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("nonce", sa.Text(), nullable=True),
        sa.Column("auth_time", sa.Integer(), nullable=False),
        sa.Column("code_challenge", sa.Text(), nullable=True),
        sa.Column(
            "code_challenge_method", sa.String(length=48), nullable=True
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["oauth2_client.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_oauth2_authorization_code_client_id"),
        "oauth2_authorization_code",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth2_authorization_code_user_id"),
        "oauth2_authorization_code",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "user",
        sa.Column(
            "latest_token_revocation_time", sa.DateTime(), nullable=True
        ),
    )
    op.drop_column("user", "refresh_token_nonce")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "refresh_token_nonce",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user", "latest_token_revocation_time")
    op.drop_index(
        op.f("ix_oauth2_authorization_code_user_id"),
        table_name="oauth2_authorization_code",
    )
    op.drop_index(
        op.f("ix_oauth2_authorization_code_client_id"),
        table_name="oauth2_authorization_code",
    )
    op.drop_table("oauth2_authorization_code")
    op.drop_table("oauth2_client")
    # ### end Alembic commands ###
