"""Create team mates on the fly

Revision ID: 2fc4745e5ad8
Revises: 456e9c17c509
Create Date: 2020-02-14 01:22:14.817274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2fc4745e5ad8"
down_revision = "456e9c17c509"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity", sa.Column("team", sa.ARRAY(sa.Integer()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity", "team")
    # ### end Alembic commands ###
