"""Add activity model

Revision ID: 324e6a66c249
Revises: 09e6a83c8272
Create Date: 2020-02-06 22:02:22.422811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "324e6a66c249"
down_revision = "09e6a83c8272"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "support",
                "drive",
                "work",
                "break",
                "rest",
                name="activitytypes",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("submitter_id", sa.Integer(), nullable=False),
        sa.Column(
            "validated",
            sa.Enum(
                "unauthorized_submitter",
                "validated",
                "pending",
                "rejected",
                name="activityvalidationstatus",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitter_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_company_id"),
        "activity",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_submitter_id"),
        "activity",
        ["submitter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_user_id"), "activity", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_user_id"), table_name="activity")
    op.drop_index(op.f("ix_activity_submitter_id"), table_name="activity")
    op.drop_index(op.f("ix_activity_company_id"), table_name="activity")
    op.drop_table("activity")
    # ### end Alembic commands ###
