"""Email activation

Revision ID: 376542d9939a
Revises: a89502b9c0f3
Create Date: 2020-09-07 11:55:56.655180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "376542d9939a"
down_revision = "a89502b9c0f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("has_activated_email", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE public.user SET has_activated_email = true")
    op.alter_column("user", "has_activated_email", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "has_activated_email")
    # ### end Alembic commands ###
