"""Add signing keys

Revision ID: 3edf5de0351f
Revises: fceb6686c112
Create Date: 2021-04-15 19:49:02.453045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3edf5de0351f"
down_revision = "fceb6686c112"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "c1b_signing_key",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column(
            "owner_type",
            sa.Enum(
                "member_state",
                "card",
                "root",
                name="signingkeyownertype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("_modulus", postgresql.BYTEA(), nullable=False),
        sa.Column("_private_exp", postgresql.BYTEA(), nullable=False),
        sa.Column("_public_exp", postgresql.BYTEA(), nullable=False),
        sa.Column("modulus_length", sa.Integer(), nullable=False),
        sa.Column("serial_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("c1b_signing_key")
    # ### end Alembic commands ###
