"""Add reception time to activity log

Revision ID: 473d9846344d
Revises: ded990280e06
Create Date: 2020-02-07 01:25:22.176162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "473d9846344d"
down_revision = "ded990280e06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity", "validated")
    op.add_column(
        "activity", sa.Column("reception_time", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "activity",
        sa.Column(
            "validation_status",
            sa.Enum(
                "unauthorized_submitter",
                "conflicting_with_history",
                "validated",
                "pending",
                "rejected",
                name="activityvalidationstatus",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity", "validation_status")
    op.drop_column("activity", "reception_time")
    op.add_column(
        "activity",
        sa.Column(
            "validated",
            sa.VARCHAR(length=22),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
