"""Add vehicle termination

Revision ID: 4e97be9e4efd
Revises: 5b7ea22cbae2
Create Date: 2020-04-07 11:29:19.428458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e97be9e4efd"
down_revision = "5b7ea22cbae2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle", sa.Column("terminated_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle", "terminated_at")
    # ### end Alembic commands ###
