"""Clean activity model

Revision ID: 5b7ea22cbae2
Revises: 299d7faa48b1
Create Date: 2020-03-31 01:12:32.625783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5b7ea22cbae2"
down_revision = "299d7faa48b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity", "mission")
    op.drop_column("activity", "team")
    op.drop_column("activity", "vehicle_registration_number")
    op.alter_column(
        "user", "company_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "company_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.add_column(
        "activity",
        sa.Column(
            "vehicle_registration_number",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "activity",
        sa.Column(
            "team",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "activity",
        sa.Column(
            "mission",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
