"""Nullable employment is_primary

Revision ID: 5bad2b03c508
Revises: c5192b34d875
Create Date: 2020-10-14 09:39:10.162177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5bad2b03c508"
down_revision = "c5192b34d875"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employment", "is_primary", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.create_check_constraint(
        "no_undefined_employment_type_for_user",
        "employment",
        "(CASE WHEN user_id is not null THEN is_primary is not null ELSE true END)",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employment", "is_primary", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_constraint("no_undefined_employment_type_for_user", "employment")
    # ### end Alembic commands ###
