"""Add admin  flag to user

Revision ID: 63b3392e68a8
Revises: 5b8a4d0e2cf4
Create Date: 2020-02-14 10:20:23.145962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63b3392e68a8"
down_revision = "5b8a4d0e2cf4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("admin", sa.Boolean(), nullable=True))
    op.execute("UPDATE public.user SET admin = false")
    op.alter_column("user", "admin", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "admin")
    # ### end Alembic commands ###
