"""company settings other task

Revision ID: 68ed4db9ae15
Revises: 890469f396e6
Create Date: 2025-07-08 15:02:23.386179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68ed4db9ae15"
down_revision = "d20f73ecb9fc"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "company", sa.Column("allow_other_task", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "company",
        sa.Column("other_task_label", sa.String(length=24), nullable=True),
    )
    op.execute(
        """
        UPDATE company
        SET allow_other_task = TRUE,
            other_task_label = ''
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "other_task_label")
    op.drop_column("company", "allow_other_task")
