"""Remove primary/secondary distinction on employments

Revision ID: 6bfdb39b721f
Revises: 1a89721126f7
Create Date: 2021-10-22 00:39:22.338857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6bfdb39b721f"
down_revision = "1a89721126f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "only_one_current_primary_employment_per_user", "employment"
    )
    op.drop_column("employment", "is_primary")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employment",
        sa.Column(
            "is_primary", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
