"""Add kilometer reading

Revision ID: 6d33809b0e9b
Revises: 76a8e05f8fee
Create Date: 2021-04-27 10:48:17.076955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d33809b0e9b"
down_revision = "76a8e05f8fee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "location_entry",
        sa.Column("kilometer_reading", sa.Integer(), nullable=True),
    )
    op.add_column(
        "location_entry",
        sa.Column(
            "kilometer_reading_received_at", sa.DateTime(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("location_entry", "kilometer_reading_received_at")
    op.drop_column("location_entry", "kilometer_reading")
