"""add regulation computation table

Revision ID: 6ff0c4124a0c
Revises: 22a0e898310e
Create Date: 2022-09-27 15:29:11.402233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6ff0c4124a0c"
down_revision = "22a0e898310e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regulation_computation",
        sa.Column(
            "creation_time",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column(
            "submitter_type",
            sa.Enum(
                "employee", "admin", name="submittertype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "day",
            "user_id",
            "submitter_type",
            name="only_one_entry_per_user_day_and_submitter_type",
        ),
    )

    op.drop_constraint(
        "activity_last_submitter_id_fkey", "activity", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "activity", "user", ["last_submitter_id"], ["id"]
    )
    op.drop_constraint(
        "only_one_control_per_controller_user_date",
        "controller_control",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "only_one_control_per_controller_user_date",
        "controller_control",
        ["controller_id", "user_id", "qr_code_generation_time"],
    )
    op.drop_constraint(None, "activity", type_="foreignkey")
    op.create_foreign_key(
        "activity_last_submitter_id_fkey",
        "activity",
        "user",
        ["last_submitter_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )

    op.drop_table("regulation_computation")
    # ### end Alembic commands ###
