"""Employment model

Revision ID: 749ceabbea95
Revises: 16ff1e79bfad
Create Date: 2020-07-20 10:05:24.619192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "749ceabbea95"
down_revision = "ff7b6a11d3e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employment",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("reception_time", sa.DateTime(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("validation_time", sa.DateTime(), nullable=True),
        sa.Column(
            "validation_status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                name="employmentrequestvalidationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("has_admin_rights", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("submitter_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitter_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employment_company_id"),
        "employment",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employment_submitter_id"),
        "employment",
        ["submitter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employment_user_id"), "employment", ["user_id"], unique=False
    )

    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        """
        ALTER TABLE employment ADD CONSTRAINT only_one_current_primary_employment_per_user
        EXCLUDE USING GIST (
            user_id WITH =,
            daterange(start_date, CASE WHEN end_date is not null THEN end_date ELSE '2100-01-01' END, '[]') WITH &&
        )
        WHERE (is_primary AND validation_status != 'rejected')
        """
    )

    op.execute(
        """
        ALTER TABLE employment ADD CONSTRAINT no_simultaneous_employments_for_the_same_company
        EXCLUDE USING GIST (
            user_id WITH =,
            company_id WITH =,
            daterange(start_date, CASE WHEN end_date is not null THEN end_date ELSE '2100-01-01' END, '[]') WITH &&
        )
        WHERE (validation_status != 'rejected')
        """
    )

    op.execute(
        """
            INSERT INTO employment(
                creation_time, 
                reception_time, 
                is_primary, 
                validation_time, 
                validation_status, 
                start_date, 
                company_id, 
                has_admin_rights, 
                user_id, 
                submitter_id
            )
            SELECT 
                NOW(),
                creation_time,
                true,
                creation_time,
                'approved',
                creation_time::date,
                company_id,
                is_company_admin,
                id,
                id
            FROM "user"
        """
    )

    op.drop_index("ix_user_company_id", table_name="user")
    op.drop_constraint("user_company_id_fkey", "user", type_="foreignkey")
    op.drop_column("user", "company_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "company_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "user_company_id_fkey", "user", "company", ["company_id"], ["id"]
    )
    op.create_index("ix_user_company_id", "user", ["company_id"], unique=False)
    op.drop_index(op.f("ix_employment_user_id"), table_name="employment")
    op.drop_index(op.f("ix_employment_submitter_id"), table_name="employment")
    op.drop_index(op.f("ix_employment_company_id"), table_name="employment")
    op.drop_table("employment")
    # ### end Alembic commands ###
