"""Update validation status

Revision ID: 74b82d635596
Revises: 473d9846344d
Create Date: 2020-02-07 10:06:15.070839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "74b82d635596"
down_revision = "473d9846344d"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_constraint("activityvalidationstatus", "activity")
    op.alter_column(
        "activity",
        "validation_status",
        type_=sa.Enum(
            "no_activity_switch",
            "unauthorized_submitter",
            "conflicting_with_history",
            "validated",
            "pending",
            "rejected",
            name="activityvalidationstatus",
            native_enum=False,
        ),
        nullable=False,
    )
    op.alter_column("activity", "type", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("activityvalidationstatus", "activity")
    op.alter_column(
        "activity",
        "validation_status",
        type_=sa.Enum(
            "unauthorized_submitter",
            "conflicting_with_history",
            "validated",
            "pending",
            "rejected",
            name="activityvalidationstatus",
            native_enum=False,
        ),
        nullable=True,
    )
    op.alter_column("activity", "type", nullable=True)
    # ### end Alembic commands ###
