"""Add vehicle_id relation on mission

Revision ID: 76a8e05f8fee
Revises: e688d06e7d2d
Create Date: 2021-04-26 10:24:09.424221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76a8e05f8fee"
down_revision = "e688d06e7d2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mission", sa.Column("vehicle_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "mission", "vehicle", ["vehicle_id"], ["id"])
    op.execute(
        "UPDATE mission SET vehicle_id = CASE WHEN context is not null THEN (context->>'vehicleId')::int ELSE NULL END, context = null"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "mission", type_="foreignkey")
    op.drop_column("mission", "vehicle_id")
    ### end Alembic commands ###
