"""Refactor start and action times

Revision ID: 7ad58d6c287d
Revises: 1f0751145e58
Create Date: 2020-03-25 11:16:34.477892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7ad58d6c287d"
down_revision = "1f0751145e58"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity", sa.Column("user_time", sa.DateTime(), nullable=True)
    )
    op.execute("UPDATE activity set user_time = start_time")
    op.alter_column("activity", "user_time", nullable=False)
    op.drop_column("activity", "start_time")

    op.add_column(
        "mission", sa.Column("user_time", sa.DateTime(), nullable=True)
    )
    op.execute("UPDATE mission set user_time = start_time")
    op.alter_column("mission", "user_time", nullable=False)
    op.drop_column("mission", "start_time")

    op.add_column(
        "team_enrollment", sa.Column("user_time", sa.DateTime(), nullable=True)
    )
    op.execute("UPDATE team_enrollment set user_time = action_time")
    op.alter_column("team_enrollment", "user_time", nullable=False)
    op.drop_column("team_enrollment", "action_time")

    op.add_column(
        "vehicle_booking", sa.Column("user_time", sa.DateTime(), nullable=True)
    )
    op.execute("UPDATE vehicle_booking set user_time = start_time")
    op.alter_column("vehicle_booking", "user_time", nullable=False)
    op.drop_column("vehicle_booking", "start_time")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity", sa.Column("start_time", sa.DateTime(), nullable=True)
    )
    op.execute("UPDATE activity set start_time = user_time")
    op.alter_column("activity", "start_time", nullable=False)
    op.drop_column("activity", "user_time")

    op.add_column(
        "mission", sa.Column("start_time", sa.DateTime(), nullable=True)
    )
    op.execute("UPDATE mission set start_time = user_time")
    op.alter_column("mission", "start_time", nullable=False)
    op.drop_column("mission", "user_time")

    op.add_column(
        "team_enrollment",
        sa.Column("action_time", sa.DateTime(), nullable=True),
    )
    op.execute("UPDATE team_enrollment set action_time = user_time")
    op.alter_column("team_enrollment", "action_time", nullable=False)
    op.drop_column("team_enrollment", "user_time")

    op.add_column(
        "vehicle_booking",
        sa.Column("start_time", sa.DateTime(), nullable=True),
    )
    op.execute("UPDATE vehicle_booking set start_time = user_time")
    op.alter_column("vehicle_booking", "start_time", nullable=False)
    op.drop_column("vehicle_booking", "user_time")
    # ### end Alembic commands ###
