"""Add user read

Revision ID: 7f8c48727acf
Revises: 4bea3bfdd457
Create Date: 2021-02-16 16:47:41.159745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f8c48727acf"
down_revision = "4bea3bfdd457"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_read_token",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("valid_until", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        op.f("ix_user_read_token_user_id"),
        "user_read_token",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_read_token_user_id"), table_name="user_read_token"
    )
    op.drop_table("user_read_token")
    # ### end Alembic commands ###
