"""Revert revision foreign key

Revision ID: 83f49fddbcb6
Revises: 55e1f2f5d706
Create Date: 2020-05-19 12:25:02.795675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83f49fddbcb6"
down_revision = "55e1f2f5d706"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "activity",
        sa.Column(
            "revised_by_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.execute(
        """
            UPDATE activity a set revised_by_id = a2.id
            FROM activity a2 where a.id = a2.revisee_id;
        """
    )
    op.drop_constraint(
        "activity_revisee_id_fkey", "activity", type_="foreignkey"
    )
    op.create_foreign_key(
        "activity_revised_by_id_fkey",
        "activity",
        "activity",
        ["revised_by_id"],
        ["id"],
    )
    op.create_index(
        "ix_activity_revised_by_id",
        "activity",
        ["revised_by_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_activity_revisee_id"), table_name="activity")
    op.drop_column("activity", "revisee_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity",
        sa.Column(
            "revisee_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "activity", type_="foreignkey")
    op.create_foreign_key(
        "activity_revisee_id_fkey",
        "activity",
        "activity",
        ["revisee_id"],
        ["id"],
    )
    op.create_index(
        "ix_activity_revisee_id", "activity", ["revisee_id"], unique=False
    )
    op.drop_index(op.f("ix_activity_revised_by_id"), table_name="activity")
    op.drop_column("activity", "revised_by_id")
    # ### end Alembic commands ###
