"""auto validations table

Revision ID: 8bc3c981ee6a
Revises: 60f5c0616731
Create Date: 2025-04-23 12:51:12.524070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8bc3c981ee6a"
down_revision = "fe1e80dc69fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mission_auto_validation",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("reception_time", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["mission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "mission_id", "is_admin", name="uq_user_mission_admin"
        ),
    )
    op.create_index(
        op.f("ix_mission_auto_validation_mission_id"),
        "mission_auto_validation",
        ["mission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mission_auto_validation_user_id"),
        "mission_auto_validation",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mission_auto_validation_reception_time"),
        "mission_auto_validation",
        ["reception_time"],
        unique=False,
    )


def downgrade():
    op.drop_index(
        op.f("ix_mission_auto_validation_reception_time"),
        table_name="mission_auto_validation",
    )
    op.drop_index(
        op.f("ix_mission_auto_validation_user_id"),
        table_name="mission_auto_validation",
    )
    op.drop_index(
        op.f("ix_mission_auto_validation_mission_id"),
        table_name="mission_auto_validation",
    )
    op.drop_table("mission_auto_validation")
