"""Add driver index field on activity

Revision ID: 8fe63e4276dc
Revises: 63b3392e68a8
Create Date: 2020-02-15 03:43:31.495806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8fe63e4276dc"
down_revision = "63b3392e68a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity", sa.Column("driver_idx", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity", "driver_idx")
    # ### end Alembic commands ###
