"""ajout champ last_submitter_id dans activity

Revision ID: 915e0942f14f
Revises: 6bfdb39b721f
Create Date: 2022-02-15 11:02:33.733812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "915e0942f14f"
down_revision = "6bfdb39b721f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity", sa.Column("last_submitter_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "activity_last_submitter_id_fkey",
        "activity",
        "user",
        ["last_submitter_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "activity_last_submitter_id_fkey", "activity", type_="foreignkey"
    )
    op.drop_column("activity", "last_submitter_id")
    # ### end Alembic commands ###
