"""reported infractions

Revision ID: 91a93a56a303
Revises: 72fba41df82f
Create Date: 2023-08-04 11:57:56.944665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "91a93a56a303"
down_revision = "72fba41df82f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "controller_control",
        sa.Column(
            "reported_infractions",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "controller_control",
        sa.Column(
            "reported_infractions_last_update_time", sa.DateTime, nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "controller_control", "reported_infractions_last_update_time"
    )
    op.drop_column("controller_control", "reported_infractions")
    # ### end Alembic commands ###
