"""Add webinars

Revision ID: 967b9aad32bb
Revises: dbfe3ea99885
Create Date: 2021-09-07 14:30:28.568261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "967b9aad32bb"
down_revision = "dbfe3ea99885"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webinar",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("title", sa.TEXT(), nullable=False),
        sa.Column("link", sa.TEXT(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("webinar")
    # ### end Alembic commands ###
