"""Make team enrollment revisable

Revision ID: a0c708394373
Revises: 19efd09533ca
Create Date: 2020-03-19 17:12:42.598485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0c708394373"
down_revision = "19efd09533ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team_enrollment", sa.Column("revisee_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_team_enrollment_revisee_id"),
        "team_enrollment",
        ["revisee_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "team_enrollment", "team_enrollment", ["revisee_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "team_enrollment", type_="foreignkey")
    op.drop_index(
        op.f("ix_team_enrollment_revisee_id"), table_name="team_enrollment"
    )
    op.drop_column("team_enrollment", "revisee_id")
    # ### end Alembic commands ###
