"""non nullable mailing lists

Revision ID: a4be56f6b1a8
Revises: e0608dcf0866
Create Date: 2021-09-15 00:37:22.418885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a4be56f6b1a8"
down_revision = "e0608dcf0866"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE "user" SET subscribed_mailing_lists = '{}' where subscribed_mailing_lists is null
    """
    )
    op.alter_column(
        "user",
        "subscribed_mailing_lists",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "subscribed_mailing_lists",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        nullable=True,
    )
    # ### end Alembic commands ###
