"""Mandatory user email

Revision ID: a89502b9c0f3
Revises: 92f5f520f6fe
Create Date: 2020-09-07 10:37:51.242964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a89502b9c0f3"
down_revision = "92f5f520f6fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("has_confirmed_email", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE public.user SET has_confirmed_email = true")
    op.alter_column("user", "has_confirmed_email", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "has_confirmed_email")
    # ### end Alembic commands ###
