"""dismiss and revision comments

Revision ID: aac0206e8581
Revises: 7ad58d6c287d
Create Date: 2020-03-25 13:05:43.541921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aac0206e8581"
down_revision = "7ad58d6c287d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity", sa.Column("dismiss_comment", sa.TEXT(), nullable=True)
    )
    op.add_column(
        "activity", sa.Column("revision_comment", sa.TEXT(), nullable=True)
    )
    op.add_column(
        "comment", sa.Column("dismiss_comment", sa.TEXT(), nullable=True)
    )
    op.add_column(
        "expenditure", sa.Column("dismiss_comment", sa.TEXT(), nullable=True)
    )
    op.add_column(
        "team_enrollment",
        sa.Column("dismiss_comment", sa.TEXT(), nullable=True),
    )
    op.add_column(
        "team_enrollment",
        sa.Column("revision_comment", sa.TEXT(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_enrollment", "revision_comment")
    op.drop_column("team_enrollment", "dismiss_comment")
    op.drop_column("expenditure", "dismiss_comment")
    op.drop_column("comment", "dismiss_comment")
    op.drop_column("activity", "revision_comment")
    op.drop_column("activity", "dismiss_comment")
    # ### end Alembic commands ###
