"""add detachment_request to employment

Revision ID: ab318bfc3ec2
Revises: ed3f60d26a7a
Create Date: 2026-07-03 10:25:25.991903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab318bfc3ec2'
down_revision = 'ed3f60d26a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employment', sa.Column('detachment_request', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employment', 'detachment_request')
    # ### end Alembic commands ###
