"""Remove event reception time

Revision ID: ad95e00a66ba
Revises: f204eb2cdb49
Create Date: 2020-03-05 12:07:14.331708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ad95e00a66ba"
down_revision = "f204eb2cdb49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity", "reception_time")
    op.drop_column("comment", "reception_time")
    op.drop_column("expenditure", "reception_time")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expenditure",
        sa.Column(
            "reception_time",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "comment",
        sa.Column(
            "reception_time",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "activity",
        sa.Column(
            "reception_time",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
