"""Add activity start time (old event time)

Revision ID: ad96684d50e1
Revises: ad95e00a66ba
Create Date: 2020-03-05 12:15:16.530814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ad96684d50e1"
down_revision = "ad95e00a66ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity", sa.Column("start_time", sa.DateTime(), nullable=True)
    )
    op.execute("UPDATE activity set start_time = event_time")
    op.alter_column("activity", "start_time", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity", "start_time")
    # ### end Alembic commands ###
