"""creation comment

Revision ID: adca0746dd7d
Revises: aac0206e8581
Create Date: 2020-03-25 13:48:20.237908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "adca0746dd7d"
down_revision = "aac0206e8581"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity", sa.Column("creation_comment", sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity", "creation_comment")
    # ### end Alembic commands ###
