"""Add activity_anonymized and activity_version_anonymized table

Revision ID: b016c0aa50e0
Revises: c8870f7b9399
Create Date: 2024-11-13 12:20:44.070879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b016c0aa50e0"
down_revision = "c8870f7b9399"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_anonymized",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("submitter_id", sa.Integer(), nullable=True),
        sa.Column("mission_id", sa.Integer(), nullable=True),
        sa.Column("dismiss_author_id", sa.Integer(), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(), nullable=True),
        sa.Column("creation_time", sa.DateTime(), nullable=True),
        sa.Column("reception_time", sa.DateTime(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("last_update_time", sa.DateTime(), nullable=True),
        sa.Column("last_submitter_id", sa.Integer(), nullable=True),
        sa.Column("dismiss_context", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "activity_version_anonymized",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=True),
        sa.Column("submitter_id", sa.Integer(), nullable=True),
        sa.Column("creation_time", sa.DateTime(), nullable=True),
        sa.Column("reception_time", sa.DateTime(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        "activity_last_submitter_id_fkey", "activity", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "activity", "user", ["last_submitter_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity_version_anonymized")
    op.drop_table("activity_anonymized")
    # ### end Alembic commands ###
