"""add expenditure setting


Revision ID: b05231a3afda
Revises: 6d33809b0e9b
Create Date: 2021-06-13 15:46:48.574707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b05231a3afda"
down_revision = "6d33809b0e9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column("require_expenditures", sa.Boolean(), nullable=True),
    )
    op.execute("UPDATE company SET require_expenditures = true")
    op.alter_column("company", "require_expenditures", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "require_expenditures")
    # ### end Alembic commands ###
