"""Remove company id from events

Revision ID: bbacbf6d536b
Revises: 4e97be9e4efd
Create Date: 2020-04-23 11:41:32.105152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bbacbf6d536b"
down_revision = "4e97be9e4efd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_activity_company_id", table_name="activity")
    op.drop_constraint(
        "activity_company_id_fkey", "activity", type_="foreignkey"
    )
    op.drop_column("activity", "company_id")
    op.drop_index("ix_comment_company_id", table_name="comment")
    op.drop_constraint(
        "comment_company_id_fkey", "comment", type_="foreignkey"
    )
    op.drop_column("comment", "company_id")
    op.drop_index("ix_expenditure_company_id", table_name="expenditure")
    op.drop_constraint(
        "expenditure_company_id_fkey", "expenditure", type_="foreignkey"
    )
    op.drop_column("expenditure", "company_id")
    op.drop_index("ix_mission_company_id", table_name="mission")
    op.drop_constraint(
        "mission_company_id_fkey", "mission", type_="foreignkey"
    )
    op.drop_column("mission", "user_time")
    op.drop_column("mission", "company_id")
    op.drop_index(
        "ix_team_enrollment_company_id", table_name="team_enrollment"
    )
    op.drop_constraint(
        "team_enrollment_company_id_fkey",
        "team_enrollment",
        type_="foreignkey",
    )
    op.drop_column("team_enrollment", "company_id")
    op.drop_index(
        "ix_vehicle_booking_company_id", table_name="vehicle_booking"
    )
    op.drop_constraint(
        "vehicle_booking_company_id_fkey",
        "vehicle_booking",
        type_="foreignkey",
    )
    op.drop_column("vehicle_booking", "company_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_booking",
        sa.Column(
            "company_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "vehicle_booking_company_id_fkey",
        "vehicle_booking",
        "company",
        ["company_id"],
        ["id"],
    )
    op.create_index(
        "ix_vehicle_booking_company_id",
        "vehicle_booking",
        ["company_id"],
        unique=False,
    )
    op.add_column(
        "team_enrollment",
        sa.Column(
            "company_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "team_enrollment_company_id_fkey",
        "team_enrollment",
        "company",
        ["company_id"],
        ["id"],
    )
    op.create_index(
        "ix_team_enrollment_company_id",
        "team_enrollment",
        ["company_id"],
        unique=False,
    )
    op.add_column(
        "mission",
        sa.Column(
            "company_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "mission",
        sa.Column(
            "user_time",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "mission_company_id_fkey", "mission", "company", ["company_id"], ["id"]
    )
    op.create_index(
        "ix_mission_company_id", "mission", ["company_id"], unique=False
    )
    op.add_column(
        "expenditure",
        sa.Column(
            "company_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "expenditure_company_id_fkey",
        "expenditure",
        "company",
        ["company_id"],
        ["id"],
    )
    op.create_index(
        "ix_expenditure_company_id",
        "expenditure",
        ["company_id"],
        unique=False,
    )
    op.add_column(
        "comment",
        sa.Column(
            "company_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "comment_company_id_fkey", "comment", "company", ["company_id"], ["id"]
    )
    op.create_index(
        "ix_comment_company_id", "comment", ["company_id"], unique=False
    )
    op.add_column(
        "activity",
        sa.Column(
            "company_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "activity_company_id_fkey",
        "activity",
        "company",
        ["company_id"],
        ["id"],
    )
    op.create_index(
        "ix_activity_company_id", "activity", ["company_id"], unique=False
    )
    # ### end Alembic commands ###
