"""Add password update time column in user

Revision ID: c00e60380604
Revises: e0834912bc9c
Create Date: 2023-01-24 10:29:26.478413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c00e60380604"
down_revision = "e0834912bc9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("password_update_time", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password_update_time")
    # ### end Alembic commands ###
