"""activation email token

Revision ID: c5192b34d875
Revises: eb2980d5acfe
Create Date: 2020-10-05 09:34:29.951010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c5192b34d875"
down_revision = "eb2980d5acfe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "activation_email_token", sa.String(length=128), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "activation_email_token")
    # ### end Alembic commands ###
