"""change siren to string

Revision ID: d2da23a44a8b
Revises: b29f8f5e455b
Create Date: 2022-08-16 09:30:00.552271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d2da23a44a8b"
down_revision = "b29f8f5e455b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("company", "siren", type_=sa.VARCHAR(length=25))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("company", "siren", type_=sa.Integer())
    # ### end Alembic commands ###
