"""Non nullable user info

Revision ID: d4f359418780
Revises: 6e70207979a9
Create Date: 2020-05-01 12:46:57.592752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d4f359418780"
down_revision = "6e70207979a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "first_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "user",
        "last_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "last_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "user",
        "first_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###
