"""non nullable expenditure type

Revision ID: d510490daadf
Revises: 475ecb05cb24
Create Date: 2020-02-11 00:04:54.807226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d510490daadf"
down_revision = "475ecb05cb24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenditure",
        "type",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenditure",
        "type",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
    )
    # ### end Alembic commands ###
