"""Ajout de la date de dépense

Revision ID: aba5d96052ab
Revises: a4be56f6b1a8
Create Date: 2021-09-28 14:00:39.676274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aba5d96052ab"
down_revision = "a4be56f6b1a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expenditure", sa.Column("spending_date", sa.DateTime(), nullable=True)
    )
    op.execute(
        """
                UPDATE expenditure e
                SET spending_date =
                    (SELECT date_trunc('day', MIN(a.start_time))
                     FROM activity a, mission m
                     WHERE m.id = a.mission_id
                     AND m.id = e.mission_id)
                     """
    )
    op.execute(
        """
            ALTER TABLE expenditure DROP CONSTRAINT no_duplicate_expenditures_per_user_and_mission;
            """
    )

    op.alter_column("expenditure", "spending_date", nullable=False)

    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        """
        ALTER TABLE expenditure ADD CONSTRAINT no_duplicate_expenditures_per_user_and_date_and_mission
        EXCLUDE USING GIST (
            user_id WITH =,
            mission_id WITH =,
            spending_date WITH =,
            type WITH =
        )
        WHERE (dismissed_at is null)
        """
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenditure", "spending_date")
    op.execute(
        """
            ALTER TABLE expenditure DROP CONSTRAINT no_duplicate_expenditures_per_user_and_date_and_mission;
            """
    )

    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        """
        ALTER TABLE expenditure ADD CONSTRAINT no_duplicate_expenditures_per_user_and_mission
        EXCLUDE USING GIST (
            user_id WITH =,
            mission_id WITH =,
            type WITH =
        )
        WHERE (dismissed_at is null)
        """
    )


# ### end Alembic commands ###
