"""add_mission_trigger_to_populate_last_active_at_in_employment

Revision ID: de1be8351df4
Revises: 1c6085670a9f
Create Date: 2025-12-16 23:22:14.012041

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de1be8351df4"
down_revision = "1c6085670a9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employment",
        sa.Column("last_active_at", sa.DateTime(), nullable=True, index=True),
    )
    op.execute(
        """
    CREATE OR REPLACE FUNCTION insert_last_active_at()
    RETURNS TRIGGER AS $$
    DECLARE
        mission_end_time TIMESTAMP;
    BEGIN
        SELECT MAX(a.end_time) INTO mission_end_time
        FROM activity a
        WHERE a.mission_id = NEW.mission_id
        AND a.user_id = NEW.user_id
        AND a.dismissed_at IS NULL
        AND a.end_time IS NOT NULL;

        IF mission_end_time IS NOT NULL THEN
            UPDATE employment e
            SET last_active_at = mission_end_time
            FROM mission m
            WHERE m.id = NEW.mission_id
            AND e.user_id = NEW.user_id
            AND e.validation_status = 'approved'
            AND e.company_id = m.company_id
            AND e.end_date IS NULL
            AND e.dismissed_at IS NULL
            AND (e.last_active_at < mission_end_time OR e.last_active_at IS NULL);
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER after_insert_mission_end
    AFTER INSERT ON mission_end
    FOR EACH ROW
    EXECUTE FUNCTION insert_last_active_at();
    """
    )
    op.execute(
        """
    UPDATE employment e
    SET last_active_at = latest.end_time
    FROM (
        SELECT DISTINCT ON (a.user_id, m.company_id)
            a.user_id,
            m.company_id,
            MAX(a.end_time) as end_time
        FROM mission_end me
        JOIN mission m ON m.id = me.mission_id
        JOIN activity a ON a.mission_id = m.id AND a.user_id = me.user_id
        WHERE a.end_time IS NOT NULL
        AND a.dismissed_at IS NULL
        GROUP BY a.user_id, m.company_id, m.id
        ORDER BY a.user_id, m.company_id, MAX(a.end_time) DESC
    ) latest
    WHERE e.user_id = latest.user_id
      AND e.company_id = latest.company_id
      AND e.validation_status = 'approved'
      AND e.end_date IS NULL
      AND e.dismissed_at IS NULL
      AND (e.last_active_at IS NULL OR e.last_active_at < latest.end_time);
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
    DROP TRIGGER IF EXISTS after_insert_mission_end ON mission_end;
    DROP FUNCTION IF EXISTS insert_last_active_at();
    """
    )
    op.drop_column("employment", "last_active_at")
    # ### end Alembic commands ###
