"""api updates

Revision ID: de90912093ef
Revises: 0722a03fd71e
Create Date: 2020-07-23 12:33:31.712641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "de90912093ef"
down_revision = "0722a03fd71e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("company", sa.Column("siren", sa.Integer(), nullable=True))
    op.add_column(
        "company",
        sa.Column("usual_name", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "company",
        sa.Column("sirets", sa.ARRAY(sa.String(length=14)), nullable=True),
    )
    op.add_column(
        "company",
        sa.Column(
            "siren_api_info",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.execute("update company set usual_name = name")
    op.drop_column("user", "is_company_admin")
    op.alter_column("company", "usual_name", nullable=False)
    op.drop_column("company", "name")
    op.add_column(
        "user", sa.Column("ssn", sa.String(length=13), nullable=True)
    )
    op.drop_column("user", "company_name_to_resolve")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "ssn")
    op.add_column(
        "user", sa.Column("is_company_admin", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "company", sa.Column("name", sa.String(length=255), nullable=True)
    )
    op.execute("update company set name = usual_name")
    op.alter_column("company", "name", nullable=False)
    op.drop_column("company", "usual_name")
    op.drop_column("company", "siren")
    op.drop_column("company", "sirets")
    op.drop_column("company", "siren_api_info")
    op.add_column(
        "user",
        sa.Column(
            "company_name_to_resolve", sa.String(length=255), nullable=True
        ),
    )
    # ### end Alembic commands ###
