"""Add first and last names to user 

Revision ID: ded990280e06
Revises: 324e6a66c249
Create Date: 2020-02-06 22:35:40.765069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ded990280e06"
down_revision = "324e6a66c249"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("first_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "user", sa.Column("last_name", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
