"""add subscribed mailing lists

Revision ID: e0608dcf0866
Revises: dbfe3ea99885
Create Date: 2021-09-07 16:41:29.934387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e0608dcf0866"
down_revision = "dbfe3ea99885"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "subscribed_mailing_lists", sa.ARRAY(sa.TEXT()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "subscribed_mailing_lists")
    # ### end Alembic commands ###
