"""Add company settings

Revision ID: e688d06e7d2d
Revises: 1e07913658d1
Create Date: 2021-04-20 18:21:57.246415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e688d06e7d2d"
down_revision = "1e07913658d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company", sa.Column("allow_team_mode", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE company SET allow_team_mode = true")
    op.alter_column("company", "allow_team_mode", nullable=False)
    op.add_column(
        "company",
        sa.Column("require_kilometer_data", sa.Boolean(), nullable=True),
    )
    op.execute("UPDATE company SET require_kilometer_data = true")
    op.alter_column("company", "require_kilometer_data", nullable=False)


def downgrade():
    op.drop_column("company", "require_kilometer_data")
    op.drop_column("company", "allow_team_mode")
    # ### end Alembic commands ###
