"""Expenditures, vehicle number and mission

Revision ID: e7e59e36d8f6
Revises: 92c1622e406a
Create Date: 2020-02-10 23:35:17.243112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e7e59e36d8f6"
down_revision = "92c1622e406a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenditure",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column("reception_time", sa.DateTime(), nullable=False),
        sa.Column(
            "validation_status",
            sa.Enum(
                "validated",
                "pending",
                "rejected",
                name="eventbasevalidationstatus",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "day_meal",
                "night_meal",
                "sleep_over",
                name="expendituretypes",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("submitter_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"],),
        sa.ForeignKeyConstraint(["submitter_id"], ["user.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expenditure_company_id"),
        "expenditure",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_expenditure_submitter_id"),
        "expenditure",
        ["submitter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_expenditure_user_id"),
        "expenditure",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "activity", sa.Column("mission", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "activity",
        sa.Column(
            "vehicle_registration_number", sa.String(length=255), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity", "vehicle_registration_number")
    op.drop_column("activity", "mission")
    op.drop_index(op.f("ix_expenditure_user_id"), table_name="expenditure")
    op.drop_index(
        op.f("ix_expenditure_submitter_id"), table_name="expenditure"
    )
    op.drop_index(op.f("ix_expenditure_company_id"), table_name="expenditure")
    op.drop_table("expenditure")
    # ### end Alembic commands ###
