"""Add parameter to enable/disable support activity

Revision ID: e9e9adb7e801
Revises: b05231a3afda
Create Date: 2021-06-13 20:52:31.981823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e9e9adb7e801"
down_revision = "b05231a3afda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column("require_support_activity", sa.Boolean(), nullable=True),
    )
    op.execute("UPDATE company SET require_support_activity = false")
    op.alter_column("company", "require_support_activity", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "require_support_activity")
    # ### end Alembic commands ###
