"""add dispute to activity

Revision ID: f134c8cd7f76
Revises: ed3f60d26a7a
Create Date: 2026-06-29 15:40:47.960773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f134c8cd7f76'
down_revision = 'ed3f60d26a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('dispute', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'dispute')
    # ### end Alembic commands ###
