"""create control pictures

Revision ID: f44c4f4ffa17
Revises: 44bebfc43b10
Create Date: 2025-02-25 11:48:37.769073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f44c4f4ffa17"
down_revision = "44bebfc43b10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "control_picture",
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("control_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["controller_control.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_control_picture_control_id"),
        "control_picture",
        ["control_id"],
        unique=False,
    )


def downgrade():
    op.drop_index(
        op.f("ix_control_picture_control_id"), table_name="control_picture"
    )
    op.drop_table("control_picture")
