"""Add disabled warnings

Revision ID: fa96dfc8237d
Revises: 3b122f77fff0
Create Date: 2021-10-04 16:16:14.802894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fa96dfc8237d"
down_revision = "3b122f77fff0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("disabled_warnings", sa.ARRAY(sa.TEXT()), nullable=True),
    )
    op.execute("""UPDATE "user" SET disabled_warnings = '{}'""")
    op.alter_column("user", "disabled_warnings", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "disabled_warnings")
    # ### end Alembic commands ###
