"""add_performance_indexes_for_invitations

Revision ID: fc7fb77ff350
Revises: 60d7e99b85f3
Create Date: 2025-01-08 15:48:53.294743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fc7fb77ff350"
down_revision = "60d7e99b85f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_email_invitation",
        "email",
        ["address", "type", "user_id", "creation_time"],
        unique=False,
        postgresql_where=sa.text("type = 'invitation' AND user_id IS NULL"),
    )
    op.create_index(
        "idx_email_type_address",
        "email",
        ["type", "address"],
        unique=False,
        postgresql_where=sa.text("type = 'scheduled_invitation'"),
    )
    op.create_index(
        "idx_employment_filters",
        "employment",
        [
            "email",
            "user_id",
            "has_admin_rights",
            "validation_status",
            "creation_time",
        ],
        unique=False,
        postgresql_where=sa.text(
            "user_id IS NULL AND has_admin_rights = false"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_employment_filters", table_name="employment")
    op.drop_index("idx_email_type_address", table_name="email")
    op.drop_index("idx_email_invitation", table_name="email")
    # ### end Alembic commands ###
