"""Revert refresh token handling

Revision ID: fceb6686c112
Revises: 119d8d9a324c
Create Date: 2021-04-06 09:27:42.213070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fceb6686c112"
down_revision = "119d8d9a324c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM refresh_token WHERE consumed_at is not null or deleted_at is not null
        """
    )
    op.drop_column("refresh_token", "consumed_at")
    op.drop_column("refresh_token", "deleted_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_token",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "refresh_token",
        sa.Column(
            "consumed_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
