from enum import Enum


class EmailType(str, Enum):
    ACCOUNT_ACTIVATION = "account_activation"
    COMPANY_CREATION = "company_creation"
    EMPLOYMENT_VALIDATION = "employment_validation_confirmation"
    INVITATION = "invitation"
    MISSION_CHANGES_WARNING = "mission_changes_warning"
    NEW_MISSION_INFORMATION = "new_mission_information"
    RESET_PASSWORD = "reset_password"
    WORKER_ONBOARDING_FIRST_INFO = "worker_onboarding_first_info"
    WORKER_ONBOARDING_SECOND_INFO = "worker_onboarding_second_info"
    MANAGER_ONBOARDING_FIRST_INFO = "manager_onboarding_first_info"
    THIRD_PARTY_ACCOUNT_CREATION = "third_party_account_creation"
    THIRD_PARTY_EMPLOYMENT_CREATION = "third_party_employment_creation"
    THIRD_PARTY_EMPLOYMENT_ACCESS = "third_party_employment_access"
    BLOCKED_ACCOUNT = "blocked_account"
    TEAM_AFFECTATION = "team_affectation"
    TEAM_NEW_COLLEAGUE = "team_new_colleague"
    COMPANY_NEVER_ACTIVE = "company_never_active"
    COMPANY_ACTIVE_THEN_INACTIVE = "company_active_then_inactive"
    COMPANY_ABOUT_TO_LOSE_CERTIFICATE = "company_about_to_lose_certificate"
    HOLIDAY_LOGGING_BY_ADMIN = "holiday_logging_by_admin"
    HOLIDAY_CHANGES_WARNING = "holiday_changes_warning"
